### ISSUE TITLE
Define Data Schema for room issues and alerts

### ISSUE THREAD

**Issue by danielwells** [byuoitav/shipwright#72]

**Comment by dannyrandall** [comment]
Some details:

A room issue will have an array of "events." Events can be alerts, comments, assigning/sending a technician, etc. A room issue will have a few other fields (start time, end time, etc) representing the current state of the issue as well.

**Comment by dannyrandall** [comment]
Ok - I figure we should get this discussion going, so here's a quick attempt at defining these structs. I imagine I'm overlooking a few things, so please give me some feedback here @bwinterton @thailandmatt @jpw547. Once we finalize things in this issue, I'll create a proposal and we can start getting it implemented.

```go
type RoomIssue struct {
    ID     string
    RoomID string
    
    Start time.Time
    End   time.Time
    
    Severity     int
    OpenAlerts   int
    ClosedAlerts int
    
    Resolution Resolution
    
    Events []Event
}

type Resolution struct {
    Code  int
    Notes string
}
```

`Events` are a little tricky - the idea here is that each event type will have it's own struct. We'll have a single unmarshal function on `eventCommon` that will unmarshal into the correct type. (or something like that - a function that uses the `type` json field to decide which struct to unmarshal into). 

```go
type EventType int

const (
    eventTypeAlertStart EventType = iota + 1
    eventTypeAlertEnd
    eventTypeNote
    eventTypePersonSent
    eventTypePersonArrived
    eventTypeChangedSeverity
)

type event interface {
    Type() EventType
    At() time.Time
    String() string
}

type eventCommon struct {
    Type EventType
    At   time.Time
}

type eventAlert struct {
    eventCommon
    
    AlertID string
}

type eventNote struct {
    eventCommon
    
    Note string
}

type eventPerson struct {
    eventCommon
    
    PersonID   string
    PersonName string
    PersonLink string
}

type eventChangedSeverity struct {
    eventCommon
    
    From int
    To int
}
```

Events can reference `Alert`s, but this is for the actual data about the alert. Actions create and modify `Alert`s. 
```go
type Alert struct {
    ID          string
    RoomIssueID string
    DeviceID    string
    
    Start time.Time
    End   time.Time
    
    AlertType string
    
    MessageLog []string
}
```

**Comment by thailandmatt** [comment]
I would say a few things:

1) Currently, the room issue has some fields for the active-alert-devices and active-alert-types for easy display in a summary view.  Do we want to continue that practice?  Or just go through the alerts and sum them up?

2) Resolution needs a second field - Code and Resolution Type or something like that

3) I think actions can affect not only alerts, but also room issues - we have that now

**Comment by dannyrandall** [comment]
1. I'm not sure that we use `active-alert-devices` anywhere in the UI right now (correct me if I'm wrong). We do use `active-alert-types` for the Alert Types list that shows up. However - the frontend is looping through all of the alerts associated with a room issue already to get the names of devices, so I don't think that having the list is particularly useful. However, you do bring up a point that I didn't address - do we want to include the list of alerts with the room issue? If we do, I would only want to store a list of `alertID`s, but we could fill in the actual data when we send it to the frontend.

2. I have both `Code` and `Notes`, do we need to add `Type` as well?

3. Actions will still be able to affect room issues, although we may create some helper-type functions to add an event.
